name:ci-cd

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0
    - name: construcao da imagem docker
      uses: docker/build-push-action@v6.18.0
      with:
        context: ./src
        file: ./src/dockerfile
        push: true
        tags: |
          acer2310/aula-kube-news:v1
          acer2310/aula-kube-news:latest
    
    
  
